version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - memcached
      - elasticsearch
    environment:
      - RAILS_ENV=development
      - MEMCACHED_URL=memcached:11211
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./db:/app/db
  memcached:
    image: memcached
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
